project:
  type: book
  output-dir: docs

execute:
   echo: false
   warning: false

book:
  title: "Datos de investigación FACSO (DAI-FACSO)"
  author: "Dirección de Investigación y Publicaciones"
  date: "last-modified"
  chapters:
    - index.qmd
    - diagnostico.qmd
    - propuesta.qmd
    - part: productos.qmd
      chapters:
       - base-principal.qmd
    
# bibliography: ocs.bib

format:
  html:
    theme: cosmo
  # pdf:
  #   documentclass: scrreprt