---
title: "Propuesta de Gestión Información DIP"
author: Dirección de Investigación y Publicaciones
toc: true
number-sections: true
format: html
---

## Diagnóstico

### Principales fuentes de información

Actualmente, las fuentes de datos sobre investigación y otros datos claves se encuentran dispersos en diferentes bases de datos, entre las que se destacan:

a)  **SEPA-VID**

Principal repositorio de proyectos de investigación en la Universidad. Permite tener acceso a proyectos adjudicados y postulados por académicos de la Universidad de Chile. La base tiene como unidad de análisis los proyectos, enummerando en columnas a los investigadores principales y coinvestigadores, así como sus ruts y afiliación institucional. Los proyectos tienen un *ID* (que parece ser interno) y un *Código*, que es un identificador proveniente de ANID o de la VID.

b)  **Repositorio ANID**

En su [repositorio en Github](https://github.com/ANID-GITHUB), ANID recopila 4 bases de datos que contienen información relevante sobre investigación en la Facultad:

-   Base de Datos Histórica Proyectos Adjudicados ANID: Incluye fondos adjudicados para concursos FONDECYT Regular, de Iniciación, Asociativos, entre otros, entre 1982 y 2025. Incluye información sobre el investigador responsable, la institución patrocinante,el monto adjudicado y, desde 2024, las palabras claves del proyecto.

-   Base de postulaciones: Además, incluye un consolidado de postulaciones ingresadas a través del Sistema de Postulación en Línea de la ANID, entre 2016 y 2024.

-   Base de Colaboración Institucional: Una base *long* de investigadores colaboradores en proyectos adjudicados por ANID entre 2016 y 2024.

-   Base de palabras claves: Palabras claves declaradas en postulaciones adjudicadas por ANID hasta el 31 de diciembre del 2023. Desde 2024 se incorporan en el histórico de proyectos adjudicados.

c)  **Base de Personal**

Si bien no está orientada directamente a la investigación, esta base es clave para caracterizar al cuerpo académico de la Facultad, incluyendo datos como género, edad, jerarquía y departamento.

d)  **RPI**

Formulario interno para gestionar el patronicio de proyectos en la Facultad. Incluye información sobre los proyectos, investigadores principales, coinvestigadores, instituciones asociadas y patrocinantes.

e)  **Colaboratorio**

Recopila información a partir de los ORCID de los académicos. Sin embargo, las bases no son tan fáciles de cruzar con otros datos. Además, no incluye a todos los académicos

f)  **Fichas académicas y CV estandarizados**

Contienen gran cantidad de información, pero no son bases de datos estructuradas, por lo que requieren mucha digitación manual. Además, sus criterios de construcción son arbitrarios y poco claros.

### Problemas identificados

Actualmente, la mayor parte del análisis depende de los datos contenidos en SEPA-VID. Sin embargo, el trabajo con este repositorio presenta una serie de problema:

-   El acceso es restringido, por lo que cualquier solicitud de datos desde otras unidades debe pasar necesariamente por la Dirección de Investigación.

-   No contiene información clave para el trabajo de la Dirección, el equipo directivo de la Facultad y otras unidades que requieran datos. Esto incluye información sobre internacionalización, género, jerarquía, departamento o edad.

-   Además, requiere procesamientos debido a inconsistencias en las etiquetas de concurso y departamento.

-   Carece de libros de códigos y de manuales de uso. En algunas columnas no hay claridad de sus definiciones y categorías.

La dispersión de los datos actuales, y las limitaciones de SEPA-VID provocan consecuencias tanto a nivel interno como externo:

-   **A nivel de gestión interna**: Limita la capacidad de generar reportes periódicos sobre el estado de de la investigación a nivel de la Facultad
-   **A nivel de requerimientos internos**: Implica que cada solicitud de datos realizada por otras unidades debe ser respondida generando reportes *adhoc*, duplicando esfuerzos y quitando tiempo para otras tareas.
-   **A nivel externo**: Quita visibilidad a los logros de la Facultad en el área de la Investigación.

En este contexto, esta propuesta busca **desarrollar un sistema local e integrado de gestión y visualización de información científica** que permita consolidar, actualizar y utilizar estratégicamente los datos de proyectos de investigación en FACSO

## Partes interesadas

+-----------------------------------------+--------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------+
| Unidad                                  | **Contraparte**                                                    | Interés                                                                                                    |
+=========================================+====================================================================+============================================================================================================+
| Dirección Académica                     | Prof. María Antonieta Urquieta, Directora.                         | Relación entre investigación y progresión académica                                                        |
|                                         |                                                                    |                                                                                                            |
|                                         | Ignacio Espinoza, Asistente                                        |                                                                                                            |
+-----------------------------------------+--------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------+
| Escuela de Postgrado                    | Prof. Catherinne Galaz, Directora.                                 | Producitividad por claustros de programas de postgrado                                                     |
|                                         |                                                                    |                                                                                                            |
|                                         | Anita Fredes, Coordinadora                                         |                                                                                                            |
|                                         |                                                                    |                                                                                                            |
|                                         | Diana Bellón, Profesional Gestión de la Información y Acreditación |                                                                                                            |
+-----------------------------------------+--------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------+
| Dirección de Género                     | Prof. Carolina Franch, Directora                                   | Tasas de adjudicación por género                                                                           |
|                                         |                                                                    |                                                                                                            |
|                                         | Pamela Saavedra, Coordinadora                                      | Proyectos de investigación que aborden temáticas de género                                                 |
+-----------------------------------------+--------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------+
| Dirección de Relaciones Internacionales | Prof. Andrés Troncoso, Director                                    | Colaboración de académicos con investigadores o instituciones internacionales                              |
|                                         |                                                                    |                                                                                                            |
|                                         | Ivania Almendra, Asistente                                         | Estancias de Investigación                                                                                 |
|                                         |                                                                    |                                                                                                            |
|                                         |                                                                    | Fondos internacionales de Investigación                                                                    |
+-----------------------------------------+--------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------+
| Departamentos                           | Directores/as y Coordinadores/as de Investigación                  | Tasas de adjudicación e historial de académicos de los departamentos                                       |
+-----------------------------------------+--------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------+
| Unidad de Educación Continua            |                                                                    | Conocer líneas de investigación de los académicos de la Facultad para crear y ofertas cursos de extensión. |
+-----------------------------------------+--------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------+
| Unidad de Innovación y Transferencia    |                                                                    | Tasas de adjudicación en proyectos de innovación y desarrollo                                              |
+-----------------------------------------+--------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------+
| Estudiantes                             |                                                                    | Conocer las líneas de investigación de los académicos de la Facultad.                                      |
+-----------------------------------------+--------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------+

## Productos

### Base de datos integrada de proyectos de investigación

En primer lugar, es necesaria la construcción de una base integrada a partir de las bases de SEPA-VID, ANID y la base de personal. La estructura de ésta es una base *long*, con los **académicos FACSO** como unidad de análisis. Para cada académico, se podrían obtener los siguientes datos:

-   Información sobre el académico: Rol del académico en el proyecto, afiliación institucional, edad, género, jerarquía.
-   Información sobre el proyecto: Identificador, Título, Concurso, Instrumento, Año de inicio y término, Investigador Responsable, monto adjudicado, palabras claves.

**Repositorio, acceso y actualización**

La base estará alojada en un repositorio en Github. Esto permitirá su actualización periódica mediante *pull-requests* por parte del equipo de la DIP.

En primera instancia, la base permanecerá en un repositorio privado para salvaguardar información potencialmente sensiblemente sobre los investigadores.

### Base de datos auxiliares

En segundo lugar, se propone construir bases auxiliares, cruzables de manera sencilla con la base principal, para facilitar el análisis de redes de colaboración con otras instituciones, tanto a nivel nacional como internacional. Estas bases seguirían los mismos criterios de acceso y actualización que la base principal.

### Visualización

Se implementará un *dashboard* para la visualización pública de datos sintéticos de investigación en la Facultad. El dashboard tendría distintas pestañas poniendo diversos enfasis en las necesidades identificadas para las diversas unidades:

1.  **Información general**: Evolución de número y tasa de adjudicación de proyectos de investigación de la Facultad.

    > *Stakeholders claves: Equipo directivo; Dirección de Investigación*

2.  **Progresión Académica**: Evolución de número y tasa de adjudicación por jerarquía académica. Diferencias en las tasas de adjudicación según resultados en los procesos de jerarquización.

    > *Stakeholders claves: Dirección Académica; Comisión de Evaluación Académica*.

3.  **Postgrado:** Proyectos adjudicados por académicos de los programas de la Facultad. Cantidad de académicos por claustro con al menos 1 proyecto adjudicados en los últimos 5 años (criterio CNA).

    > *Stakeholders claves: Dirección de Postgrado; Programas de Postgrado*

4.  **Género**: Cantidad de proyectos de investigación adjudicados que tratan temas sobre género. Cantidad de proyectos con Investigadoras Reponsables mujeres en la Facultad.

    > *Stakeholders claves: Dirección de Género*

5.  **Redes e Internacionalización**: Redes de colaboración con académicos e institucionales internacionales y nacionales. Proyectos internacionales adjudicados.

    > *Stakeholders claves: Dirección de Relaciones Internacionales; Unidad de Innovación y Transferencia*

6.  **Innovación**: Tasas de adjudicación de proyectos de innovación y desarrollo.

    > *Stakeholders claves: Unidad de Innovación y Transferencia*

7.  **Líneas de Investigación**: Nube y redes de palabras claves en projectos adjudicados en la Facultad

    > *Stakeholders claves: Unidad de Educación Continua; Estudiantes*

### Reportes

Eventualmente, se podría dar la opción de reportes a nivel agregado e individual. Esto requeriría crear accesos diferenciados para distintos actores de la Facultad. Por ejemplo:

-   Equipo Directivo de la Facultad: Datos agregados a nivel de Facultad y departamentos
-   Directores de departamento (o coordinadores de investigación): Acceso a datos generales e individuales de su departamento
-   Académicos: Acceso a un reporte personal.

### Documentación

El repositorio de las bases debe incluir documentación clara sobre la construcción de las bases de datos y el visualizador, incluyendo libros de códigos y reportes técnicos.

## Cronograma

+----------------------------------------+-------+--------+------------+---------+-----------+-----------+
| Actividad                              | Julio | Agosto | Septiembre | Octubre | Noviembre | Diciembre |
+========================================+=======+========+============+=========+===========+===========+
| Acuerdo plan de trabajo                | X     |        |            |         |           |           |
+----------------------------------------+-------+--------+------------+---------+-----------+-----------+
| Consolidación base de datos principal  | X     | X      |            |         |           |           |
+----------------------------------------+-------+--------+------------+---------+-----------+-----------+
| Consolidación base de datos auxiliares |       | X      |            |         |           |           |
+----------------------------------------+-------+--------+------------+---------+-----------+-----------+
| Construcción del dashboard             |       |        | X          | X       |           |           |
+----------------------------------------+-------+--------+------------+---------+-----------+-----------+
| Construcción sistema de reportes       |       |        | X          | X       |           |           |
+----------------------------------------+-------+--------+------------+---------+-----------+-----------+
| Testeo y retroalimentación             |       |        |            |         | X         |           |
+----------------------------------------+-------+--------+------------+---------+-----------+-----------+
| Publicación                            |       |        |            |         |           | X         |
+----------------------------------------+-------+--------+------------+---------+-----------+-----------+
